apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: bank-ronald-express-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: bank-ronald-express-pipeline
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: ronald-chan-pvc
